
#import "ViewController_MyListScreen.h"
#import "ViewController_EventContentScreen.h"

@interface ViewController_MyListScreen ()

@property (strong, nonatomic) IBOutlet UITableView *myTableView;

@end

@implementation ViewController_MyListScreen

- (void)viewDidLoad {
    [super viewDidLoad];
    
    _db = [FIRFirestore firestore];
//    eventImageNames = [NSMutableArray arrayWithArray:@[@"image3", @"image2", @"image3"]];
//    eventNames = [NSMutableArray arrayWithArray:@[@"Ultra Festival 2021", @"Blackpink Worldtour 2022", @"Comic con"]];
//    eventDate = [NSMutableArray arrayWithArray:@[@"24 Oct - 28 Oct", @"30 Nov - 02 Dec", @"01 Jan - 5Jan"]];
    objectListOfUserEvents = [[NSMutableDictionary alloc]initWithCapacity:5];

    [[self.db collectionWithPath:@"userEvents"]
        getDocumentsWithCompletion:^(FIRQuerySnapshot *snapshot, NSError *error) {
          if (error != nil) {
            NSLog(@"Error getting documents: %@", error);
          } else {
            for (FIRDocumentSnapshot *document in snapshot.documents) {
                NSString *key = document.documentID;
                NSDictionary *eventDetail = document.data;
                [self -> objectListOfUserEvents setObject:eventDetail forKey:key];
            }
              NSLog(@"self -> categoryItems = %@", self -> objectListOfUserEvents);
              [self.myTableView reloadData];
          }
        }];
}

// Add new events to user lists which generated by users
- (IBAction)addEventMethod:(id)sender {
    UIStoryboard *sb = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
    ViewController_AddEvent *nextScreen = [sb instantiateViewControllerWithIdentifier:@"ViewController_AddEvent"];
    [self presentViewController:nextScreen animated:YES completion:nil];
}

#pragma mark - UITableView DataSource methods

- (NSInteger)tableView:( UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return [objectListOfUserEvents count];
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    static NSString *cellId = @"cell";
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:cellId forIndexPath:indexPath];
    
//    cell.imageView.image = [UIImage imageNamed:eventImageNames[indexPath.row]];
    
    // Initialise the NSString where to assign the data from firebase
    NSString *eventNo = [objectListOfUserEvents allKeys][indexPath.row];
    NSString *eventName = objectListOfUserEvents [eventNo][@"name"];
    NSString *eventDate = objectListOfUserEvents [eventNo][@"date"];
    
    cell.textLabel.text = eventName;
    cell.detailTextLabel.text = eventDate;
    
    return cell;
}


// Delete the row method
- (void)tableView:(UITableView *)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath *)indexPath {
    if (editingStyle == UITableViewCellEditingStyleDelete) {
        
        [objectListOfUserEvents removeObjectForKey:indexPath];
        [tableView deleteRowsAtIndexPaths:[NSArray arrayWithObject:indexPath] withRowAnimation:UITableViewRowAnimationFade];
    }
}

// Go to content screen
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    
//    UIStoryboard *sb = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
//    ViewController_EventContentScreen *nextScreen = [sb instantiateViewControllerWithIdentifier:@"ViewController_EventContentScreen"];
//
//    [self presentViewController:nextScreen animated:YES completion:nil];
    //NSLog(@"You slected a row: ");
    NSString *itemclicked = objectListOfUserEvents[indexPath];

}

// adjust the size of cell
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath {
    return 100;
}


@end
